import csv
import yaml
import copy
import os
import time



import click
import humanize

from pathvalidate import is_valid_filename, sanitize_filename
from panoptes_cli.scripts.panoptes import cli
from panoptes_client import Subject
from panoptes_client.panoptes import PanoptesAPIException

LINK_BATCH_SIZE = 10
MAX_PENDING_SUBJECTS_ATTACHED_MEDIA = 50
MAX_UPLOAD_FILE_SIZE = 1024 * 1024
CURRENT_STATE_VERSION = 1


@cli.group()
def subject():
    """Contains commands for managing subjects."""

    pass


@subject.command()
@click.option(
    "--subject-set-id",
    "-s",
    help="List subjects from the given subject set.",
    type=int,
    required=False,
)
@click.option(
    "--quiet",
    "-q",
    is_flag=True,
    help="Only print subject IDs (omit media URLs).",
)
@click.argument("subject-ids", type=int, required=False, nargs=-1)
def ls(subject_set_id, quiet, subject_ids):
    """
    Lists subject IDs and their media URLs.
    """

    if subject_ids:
        for subject_id in subject_ids:
            subject = Subject.find(subject_id)
            if quiet:
                click.echo(subject.id)
            else:
                echo_subject(subject)
        return

    subjects = Subject.where(subject_set_id=subject_set_id)
    if quiet:
        click.echo(" ".join([s.id for s in subjects]))
    else:
        for subject in subjects:
            echo_subject(subject)

@subject.command(name='upload-subjects-attached-media')
@click.argument('manifest-files', required=True, nargs=-1)
@click.option(
    '--allow-missing',
    '-M',
    help=("Do not abort when creating subjects with no media files."),
    is_flag=True,
)
@click.option(
    '--remote-location',
    '-r',
    help=(
        "Specify a field (by column number) in the manifest which contains a "
        "URL to a remote media location. Can be used more than once."
    ),
    multiple=True,
    type=int,
    required=False,
)
@click.option(
    '--mime-type',
    '-m',
    help=(
        "MIME type for remote media. Defaults to image/png. Can be used more "
        "than once, in which case types are mapped one to one with remote "
        "locations in the order they are given. Has no effect without "
        "--remote-location."
    ),
    type=str,
    required=False,
    default=('image/png',),
    multiple=True
)
@click.option(
    '--file-column',
    '-f',
    help=(
        "Specify a field (by column number) in the manifest which contains a "
        "local file to be uploaded. Can be used more than once. Disables auto-"
        "detection of filename columns."
    ),
    multiple=True,
    type=int,
    required=False,
)
def upload_subjects_attached_media(
    manifest_files,
    allow_missing,
    remote_location,
    mime_type,
    file_column
):
    """
    Uploads attached_media associated to subjects from each of the given MANIFEST_FILES.

    Example with only local files:

    $ panoptes subject upload-subjects-attached-media  manifest.csv

    eg csv
    subject_id | file_name_1 | file_name_2 | metadata

    Local filenames will be automatically detected in the manifest and
    uploaded, or filename columns can be specified with --file-column.

    If you are hosting your media yourself, you can put the URLs in the
    manifest and specify the column number(s):

    $ panoptes subject upload-subjects-attached-media -r 1  manifest.csv

    $ panoptes subject upload-subjects-attached-media -r 1 -r 2  manifest.csv

    Any local files will still be detected and uploaded.
    """
    if (
        len(manifest_files) > 1
        and any(map(lambda m: m.endswith('.yaml'), manifest_files))
    ):
        click.echo(
            'Error: YAML manifests must be processed one at a time.',
            err=True,
        )
        return -1
    elif manifest_files[0].endswith('.yaml'):
        with open(manifest_files[0], 'r') as yaml_manifest:
            upload_state = yaml.load(yaml_manifest, Loader=yaml.FullLoader)
        if upload_state['state_version'] > CURRENT_STATE_VERSION:
            click.echo(
                'Error: {} was generated by a newer version of the Panoptes '
                'CLI and is not compatible with this version.'.format(
                    manifest_files[0],
                ),
                err=True,
            )
            return -1
        resumed_upload = True
    else:
        upload_state = {
            'state_version': CURRENT_STATE_VERSION,
            'manifest_files': manifest_files,
            'allow_missing': allow_missing,
            'remote_location': remote_location,
            'mime_type': mime_type,
            'file_column': file_column,
            'waiting_to_upload': []
        }
        resumed_upload = False

    remote_location_count = len(upload_state['remote_location'])
    mime_type_count = len(upload_state['mime_type'])
    if remote_location_count > 1 and mime_type_count == 1:
        upload_state['mime_type'] = (
            upload_state['mime_type'] * remote_location_count
        )
    elif remote_location_count > 0 and mime_type_count != remote_location_count:
        click.echo(
            'Error: The number of MIME types given must be either 1 or equal '
            'to the number of remote locations.',
            err=True,
        )
        return -1

    if not resumed_upload:
        subject_rows = []
        subjects_by_id = {}
        for manifest_file in upload_state['manifest_files']:
            with open(manifest_file) as manifest_f:
                file_root = os.path.dirname(manifest_file)
                r = csv.reader(manifest_f, skipinitialspace=True)
                headers = next(r)
                for row_number, row in enumerate(r, start=1):
                    metadata = dict(zip(headers, row))
                    files = []
                    if not metadata.get('subject_id'):
                        click.echo(f'Missing subject_id in row:{row_number}', err=True)
                        return -1
                    subject_id = metadata['subject_id']
                    try:
                        subject_id = int(subject_id)
                    except ValueError:
                        click.echo(f'Invalid subject_id in row: {row_number}')
                        return -1
                    try:
                        subject = Subject.find(subject_id)
                        subjects_by_id[subject_id] = subject
                    except PanoptesAPIException:
                        click.echo(f'Subject {subject_id} does not exist on row: {row_number}')
                        return -1
                    if not upload_state['file_column']:
                        upload_state['file_column'] = []
                        for field_num, col in enumerate(row, start=1):
                            file_path = os.path.join(file_root, col)
                            if os.path.exists(file_path):
                                upload_state['file_column'].append(field_num,)
                            if _validate_file(file_path):
                                files.append(file_path)
                            elif not upload_state['allow_missing']:
                                return -1
                    else:
                        for field_num in upload_state['file_column']:
                            file_path = os.path.join(
                                file_root,
                                row[field_num - 1]
                            )
                            if _validate_file(file_path):
                                files.append(file_path)
                            elif not upload_state['allow_missing']:
                                return -1

                    for field_num, _mime_type in zip(upload_state['remote_location'], upload_state['mime_type'],):
                        files.append({_mime_type: row[field_num - 1]})

                    if len(files) == 0:
                        click.echo(
                            'Could not find any files in row:',
                            err=True,
                        )
                        click.echo(','.join(row), err=True)
                        if not upload_state['allow_missing']:
                            return -1
                        else:
                            continue
                    subject_rows.append((subject_id, files, metadata))

                if not subject_rows:
                    click.echo(
                        'File {} did not contain any rows.'.format(
                            manifest_file,
                        ),
                        err=True,
                    )
                    return -1
        subject_rows = list(enumerate(subject_rows))
        upload_state['waiting_to_upload'] = copy.deepcopy(subject_rows)
    else:
        subjects_by_id = {}
        for _, (subject_id, _, _) in upload_state['waiting_to_upload']:
            try:
                subject = Subject.find(subject_id)
                subjects_by_id[subject_id] = subject
            except PanoptesAPIException:
                click.echo(f'Subject {subject_id} does not exist', err=True)
                return -1
        subject_rows = copy.deepcopy(upload_state['waiting_to_upload'])

    pending_attached_media = []

    def move_created(limit):
        while len(pending_attached_media) > limit:
            for media_futures, subject_row in pending_attached_media:
                if all(media_future.done() for media_future in media_futures):
                    pending_attached_media.remove((media_futures, subject_row))
                    upload_state['waiting_to_upload'].remove(subject_row)
            time.sleep(0.5)

    with click.progressbar(
        subject_rows,
        length=len(subject_rows),
        label='Uploading subject attached media',
    ) as _subject_rows:
        try:
            with Subject.async_saves():
                for subject_row in _subject_rows:
                    _, (subject_id, files, metadata) = subject_row
                    subject = subjects_by_id[subject_id]
                    media_futures = []
                    for media_file in files:
                        media_futures.append(subject.save_attached_image(media_file))
                    pending_attached_media.append((media_futures, subject_row))

                    move_created(MAX_PENDING_SUBJECTS_ATTACHED_MEDIA)

            move_created(0)
        finally:
            if (len(pending_attached_media) > 0):
                click.echo('Error: Upload failed.', err=True)
                if click.confirm(
                    'Would you like to save the upload state to resume the '
                    'upload later?',
                    default=True,
                ):
                    while True:
                        state_file_name = 'panoptes-upload-attached-media.yaml'

                        state_file_name = click.prompt('Enter filename to save to', default=state_file_name,)

                        if not state_file_name.endswith('.yaml'):
                            click.echo(
                                'Error: File name must end in ".yaml".',
                                err=True,
                            )
                            if click.confirm(
                                'Save to {}.yaml?'.format(state_file_name),
                                default=True,
                            ):
                                state_file_name += '.yaml'
                            else:
                                continue
                        if not is_valid_filename(state_file_name):
                            click.echo(
                                f'Error: {state_file_name} is not a valid file name',
                                err=True,
                            )
                            sanitized_filename = sanitize_filename(state_file_name,)
                            if click.confirm(f'Save to {sanitized_filename}', default=True,):
                                state_file_name = sanitized_filename
                            else:
                                continue
                        if os.path.exists(state_file_name):
                            if not click.confirm(f'File {state_file_name} already exists. Overwrite?', default=False,):
                                continue
                        break

                    with open(state_file_name, 'w') as state_file:
                        yaml.dump(upload_state, state_file)

@subject.command()
@click.argument("subject-id", required=True)
def info(subject_id):
    subject = Subject.find(subject_id)
    click.echo(yaml.dump(subject.raw))


@subject.command()
@click.option(
    "--force",
    "-f",
    is_flag=True,
    help="Delete without asking for confirmation.",
)
@click.argument("subject-ids", required=True, nargs=-1, type=int)
def delete(force, subject_ids):
    for subject_id in subject_ids:
        if not force:
            click.confirm("Delete subject {}?".format(subject_id), abort=True)
        Subject.find(subject_id).delete()


@subject.command()
@click.option(
    "--replace",
    "-r",
    is_flag=True,
    help="Replace all existing metadata rather than merging.",
)
@click.argument("metadata-file", required=True, nargs=1)
def update_metadata(replace, metadata_file):
    """
    Updates subject metadata from a CSV file.

    The CSV file should contain a "subject_id" column listing subject IDs.
    All other column names are taken to be metadata keys.
    """
    with open(metadata_file, "r") as metadata_f:
        total_tows = len(metadata_f.readlines())
        metadata_f.seek(0)
        metadata_rows = csv.DictReader(metadata_f)
        with click.progressbar(
            metadata_rows,
            length=total_tows,
            label="Update subject metadata",
        ) as _metadata_rows:
            for metadata in _metadata_rows:
                subject_id = metadata.pop("subject_id")
                try:
                    subject = Subject.find(subject_id)
                    if replace:
                        subject.metadata = dict(metadata)
                    else:
                        subject.metadata.update(metadata)
                    subject.save()
                except Exception as e:
                    click.echo(f"Failed to update subject {subject_id}: {e}", err=True)


def echo_subject(subject):
    m = map(lambda l: list(l.values())[0], subject.locations)
    click.echo("{} {}".format(subject.id, " ".join(m)))


def _validate_file(file_path):
    if not os.path.isfile(file_path):
        click.echo(
            'Error: File "{}" could not be found.'.format(
                file_path,
            ),
            err=True,
        )
        return False

    file_size = os.path.getsize(file_path)
    if file_size == 0:
        click.echo(
            'Error: File "{}" is empty.'.format(
                file_path,
            ),
            err=True,
        )
        return False
    elif file_size > MAX_UPLOAD_FILE_SIZE:
        click.echo(
            'Error: File "{}" is {}, larger than the maximum {}.'.format(
                file_path,
                humanize.naturalsize(file_size),
                humanize.naturalsize(MAX_UPLOAD_FILE_SIZE),
            ),
            err=True,
        )
        return False
    return True
